// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29/1/2026, 17:06:50
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/blueb/Downloads/Portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/blueb/Downloads/Portfolio/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/blueb/Downloads/Portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/blueb/Downloads/Portfolio/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/blueb/Downloads/Portfolio/app/plugins/**/*.{js,ts,mjs}","C:/Users/blueb/Downloads/Portfolio/app/composables/**/*.{js,ts,mjs}","C:/Users/blueb/Downloads/Portfolio/app/utils/**/*.{js,ts,mjs}","C:/Users/blueb/Downloads/Portfolio/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/blueb/Downloads/Portfolio/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/blueb/Downloads/Portfolio/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/blueb/Downloads/Portfolio/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;